title: Nasser Boan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cientista de Dados 
  <br><br>
  Professor 
  <br><br>
  <a href="https://www.linkedin.com/in/nasser-boan-2b264a85/">Meu linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-164158275-1 # your Google Analytics tracking ID here
